### ISSUE TITLE
Epic 1. Implement ML to choose suitable employees for the vacancy

### ISSUE THREAD

**Issue by viktormurashov** [ISUCT/employees#1]
- [ ] Investigate about how choose users with more accuracy with ML #2 

- [ ] Add server part for ML #5 

- [ ] Implement ability to call ML with API from UI and show results #6 

May be I miss some steps please describe all this part and if you need add more issue for Epic 1
